### ISSUE TITLE
node seed.js fails

### ISSUE THREAD

**Issue by r-wells** [mosh-hamedani/vidly-api-node#15]
I'm running through the React course now and just installed MongoDB. I run `node seed.js` and get the error:

```
Ryan@DESKTOP-ILLP59F MINGW64 ~/Desktop/code-projects/react/Section 8- Calling Backend Services/start/vidly-api-node (master)
$ node seed.js
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'joi'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\Ryan\Desktop\code-projects\react\Section 8-
Calling Backend Services\start\vidly-api-node\models\genre.js:1:13)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```
Is joi not initialized on the project?

**Comment by rustemjantayev** [comment]
Yes, you have to install it
