### ISSUE TITLE
Node.js course - Error connecting to MongoDB in Heroku deploy

### ISSUE THREAD

**Issue by MrPaz** [mosh-hamedani/vidly-api-node#16]
Very last video of the Node.js course, and I'm ending with an unresolved error which is frustrating.  The steps for setting up a free mLab account for 500mb of storage is a bit different now (it transfers you to MongoDB Atlas, rather than doing everything in mLab now), but I think I did everything Mosh did, but am stuck, unable to connect to MongoDB.  I've looked at logs and documentation for two hours and can't come up with anything, and reviewed the videos to make sure I didn't miss anything.  

One portion of the log says it failed at the start script, also says failed to connect to server, and the uncaughtException.log file also says failed to connect to server connection refused.  I'm not sure why this is happening.  Any help would be much appreciated.  

Here is my log:
`>heroku logs
2019-09-10T22:24:39.000000+00:00 app[api]: Build started by user randombsthrowaway@gmail.com
2019-09-10T22:25:36.350660+00:00 heroku[web.1]: State changed from crashed to starting
2019-09-10T22:25:35.910501+00:00 app[api]: Deploy 93a36670 by user randombsthrowaway@gmail.com
2019-09-10T22:25:35.910501+00:00 app[api]: Release v7 created by user randombsthrowaway@gmail.com
2019-09-10T22:25:36.000000+00:00 app[api]: Build succeeded
2019-09-10T22:25:38.839155+00:00 heroku[web.1]: Starting process with command `npm start`
2019-09-10T22:25:40.904305+00:00 app[web.1]:
2019-09-10T22:25:40.904322+00:00 app[web.1]: > Vidly_Node.js@1.0.0 start /app
2019-09-10T22:25:40.904324+00:00 app[web.1]: > node index.js
2019-09-10T22:25:40.904326+00:00 app[web.1]:
2019-09-10T22:25:41.618034+00:00 app[web.1]: WARNING: NODE_ENV value of 'production' did not match any deployment config file names.
2019-09-10T22:25:41.618562+00:00 app[web.1]: WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
2019-09-10T22:25:41.841717+00:00 app[web.1]: (node:23) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
2019-09-10T22:25:41.844331+00:00 app[web.1]: {"message":"Listening on port 5000...","level":"info"}
2019-09-10T22:25:42.022695+00:00 app[web.1]: {"error":{"name":"MongoNetworkError","errorLabels":["TransientTransactionError"]},"level":"error","message":"uncaughtException: failed to connect to server [vidly-shard-00-01-9gnfk.mongodb.net:27017] on first connect [MongoNetworkError: connection 5 to vidly-shard-00-01-9gnfk.mongodb.net:27017 closed]\nMongoNetworkError: failed to connect to server [vidly-shard-00-01-9gnfk.mongodb.net:27017] on first connect [MongoNetworkError: connection 5 to vidly-shard-00-01-9gnfk.mongodb.net:27017 closed]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:431:11)\n    at Pool.emit (events.js:198:13)\n    at connect (/app/node_modules/mongodb-core/lib/connection/pool.js:557:14)\n    at callback (/app/node_modules/mongodb-core/lib/connection/connect.js:109:5)\n    at runCommand (/app/node_modules/mongodb-core/lib/connection/connect.js:129:7)\n    at Connection.errorHandler (/app/node_modules/mongodb-core/lib/connection/connect.js:321:5)\n    at Object.onceWrapper (events.js:286:20)\n    at Connection.emit (events.js:198:13)\n    at TLSSocket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:350:12)\n    at Object.onceWrapper (events.js:286:20)\n    at TLSSocket.emit (events.js:198:13)\n    at _handle.close (net.js:606:12)\n    at TCP.done (_tls_wrap.js:388:7)","stack":"MongoNetworkError: failed to connect to server [vidly-shard-00-01-9gnfk.mongodb.net:27017] on first connect [MongoNetworkError: connection 5 to vidly-shard-00-01-9gnfk.mongodb.net:27017 closed]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:431:11)\n    at Pool.emit (events.js:198:13)\n    at connect (/app/node_modules/mongodb-core/lib/connection/pool.js:557:14)\n    at callback (/app/node_modules/mongodb-core/lib/connection/connect.js:109:5)\n    at runCommand (/app/node_modules/mongodb-core/lib/connection/connect.js:129:7)\n    at Connection.errorHandler (/app/node_modules/mongodb-core/lib/connection/connect.js:321:5)\n    at Object.onceWrapper (events.js:286:20)\n    at Connection.emit (events.js:198:13)\n    at TLSSocket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:350:12)\n    at Object.onceWrapper (events.js:286:20)\n    at TLSSocket.emit (events.js:198:13)\n    at _handle.close (net.js:606:12)\n    at TCP.done (_tls_wrap.js:388:7)","exception":true,"date":"Tue Sep 10 2019 22:25:42 GMT+0000 (Coordinated Universal Time)","process":{"pid":23,"uid":22531,"gid":22531,"cwd":"/app","execPath":"/app/.heroku/node/bin/node","version":"v10.16.0","argv":["/app/.heroku/node/bin/node","/app/index.js"],"memoryUsage":{"rss":82886656,"heapTotal":62169088,"heapUsed":25412032,"external":18262612}},"os":{"loadavg":[3.90625,6.11376953125,8.89306640625],"uptime":892987},"trace":[{"column":11,"file":"/app/node_modules/mongodb-core/lib/topologies/server.js","function":null,"line":431,"method":null,"native":false},{"column":13,"file":"events.js","function":"Pool.emit","line":198,"method":"emit","native":false},{"column":14,"file":"/app/node_modules/mongodb-core/lib/connection/pool.js","function":"connect","line":557,"method":null,"native":false},{"column":5,"file":"/app/node_modules/mongodb-core/lib/connection/connect.js","function":"callback","line":109,"method":null,"native":false},{"column":7,"file":"/app/node_modules/mongodb-core/lib/connection/connect.js","function":"runCommand","line":129,"method":null,"native":false},{"column":5,"file":"/app/node_modules/mongodb-core/lib/connection/connect.js","function":"Connection.errorHandler","line":321,"method":"errorHandler","native":false},{"column":20,"file":"events.js","function":"Object.onceWrapper","line":286,"method":"onceWrapper","native":false},{"column":13,"file":"events.js","function":"Connection.emit","line":198,"method":"emit","native":false},{"column":12,"file":"/app/node_modules/mongodb-core/lib/connection/connection.js","function":null,"line":350,"method":null,"native":false},{"column":20,"file":"events.js","function":"Object.onceWrapper","line":286,"method":"onceWrapper","native":false},{"column":13,"file":"events.js","function":"TLSSocket.emit","line":198,"method":"emit","native":false},{"column":12,"file":"net.js","function":"_handle.close","line":606,"method":"close","native":false},{"column":7,"file":"_tls_wrap.js","function":"TCP.done","line":388,"method":"done","native":false}]}
2019-09-10T22:25:45.115380+00:00 heroku[web.1]: State changed from starting to crashed
2019-09-10T22:25:45.035380+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2019-09-10T22:25:45.035882+00:00 app[web.1]: npm ERR! errno 1
2019-09-10T22:25:45.037140+00:00 app[web.1]: npm ERR! Vidly_Node.js@1.0.0 start: `node index.js`
2019-09-10T22:25:45.037317+00:00 app[web.1]: npm ERR! Exit status 1
2019-09-10T22:25:45.039203+00:00 app[web.1]: npm ERR!
2019-09-10T22:25:45.039592+00:00 app[web.1]: npm ERR! Failed at the Vidly_Node.js@1.0.0 start script.
2019-09-10T22:25:45.039950+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2019-09-10T22:25:45.048694+00:00 app[web.1]:
2019-09-10T22:25:45.048842+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2019-09-10T22:25:45.048919+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2019-09-10T22_25_45_042Z-debug.log
2019-09-10T22:25:45.099192+00:00 heroku[web.1]: Process exited with status 1`

This is what I could make out to be the relevant portion of the uncaughtExceptions.log file:
`{"error":{"name":"MongoNetworkError","errorLabels":["TransientTransactionError"]},"level":"error","message":"uncaughtException: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\nMongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous>`

**Comment by MrPaz** [comment]
It's actually easier to read the first log when it's not formatted as code:

>heroku logs
2019-09-10T22:24:39.000000+00:00 app[api]: Build started by user randombsthrowaway@gmail.com
2019-09-10T22:25:36.350660+00:00 heroku[web.1]: State changed from crashed to starting
2019-09-10T22:25:35.910501+00:00 app[api]: Deploy 93a36670 by user randombsthrowaway@gmail.com
2019-09-10T22:25:35.910501+00:00 app[api]: Release v7 created by user randombsthrowaway@gmail.com
2019-09-10T22:25:36.000000+00:00 app[api]: Build succeeded
2019-09-10T22:25:38.839155+00:00 heroku[web.1]: Starting process with command `npm start`
2019-09-10T22:25:40.904305+00:00 app[web.1]:
2019-09-10T22:25:40.904322+00:00 app[web.1]: > Vidly_Node.js@1.0.0 start /app
2019-09-10T22:25:40.904324+00:00 app[web.1]: > node index.js
2019-09-10T22:25:40.904326+00:00 app[web.1]:
2019-09-10T22:25:41.618034+00:00 app[web.1]: WARNING: NODE_ENV value of 'production' did not match any deployment config file names.
2019-09-10T22:25:41.618562+00:00 app[web.1]: WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
2019-09-10T22:25:41.841717+00:00 app[web.1]: (node:23) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
2019-09-10T22:25:41.844331+00:00 app[web.1]: {"message":"Listening on port 5000...","level":"info"}
2019-09-10T22:25:42.022695+00:00 app[web.1]: {"error":{"name":"MongoNetworkError","errorLabels":["TransientTransactionError"]},"level":"error","message":"uncaughtException: failed to connect to server [vidly-shard-00-01-9gnfk.mongodb.net:27017] on first connect [MongoNetworkError: connection 5 to vidly-shard-00-01-9gnfk.mongodb.net:27017 closed]\nMongoNetworkError: failed to connect to server [vidly-shard-00-01-9gnfk.mongodb.net:27017] on first connect [MongoNetworkError: connection 5 to vidly-shard-00-01-9gnfk.mongodb.net:27017 closed]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:431:11)\n    at Pool.emit (events.js:198:13)\n    at connect (/app/node_modules/mongodb-core/lib/connection/pool.js:557:14)\n    at callback (/app/node_modules/mongodb-core/lib/connection/connect.js:109:5)\n    at runCommand (/app/node_modules/mongodb-core/lib/connection/connect.js:129:7)\n    at Connection.errorHandler (/app/node_modules/mongodb-core/lib/connection/connect.js:321:5)\n    at Object.onceWrapper (events.js:286:20)\n    at Connection.emit (events.js:198:13)\n    at TLSSocket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:350:12)\n    at Object.onceWrapper (events.js:286:20)\n    at TLSSocket.emit (events.js:198:13)\n    at _handle.close (net.js:606:12)\n    at TCP.done (_tls_wrap.js:388:7)","stack":"MongoNetworkError: failed to connect to server [vidly-shard-00-01-9gnfk.mongodb.net:27017] on first connect [MongoNetworkError: connection 5 to vidly-shard-00-01-9gnfk.mongodb.net:27017 closed]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:431:11)\n    at Pool.emit (events.js:198:13)\n    at connect (/app/node_modules/mongodb-core/lib/connection/pool.js:557:14)\n    at callback (/app/node_modules/mongodb-core/lib/connection/connect.js:109:5)\n    at runCommand (/app/node_modules/mongodb-core/lib/connection/connect.js:129:7)\n    at Connection.errorHandler (/app/node_modules/mongodb-core/lib/connection/connect.js:321:5)\n    at Object.onceWrapper (events.js:286:20)\n    at Connection.emit (events.js:198:13)\n    at TLSSocket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:350:12)\n    at Object.onceWrapper (events.js:286:20)\n    at TLSSocket.emit (events.js:198:13)\n    at _handle.close (net.js:606:12)\n    at TCP.done (_tls_wrap.js:388:7)","exception":true,"date":"Tue Sep 10 2019 22:25:42 GMT+0000 (Coordinated Universal Time)","process":{"pid":23,"uid":22531,"gid":22531,"cwd":"/app","execPath":"/app/.heroku/node/bin/node","version":"v10.16.0","argv":["/app/.heroku/node/bin/node","/app/index.js"],"memoryUsage":{"rss":82886656,"heapTotal":62169088,"heapUsed":25412032,"external":18262612}},"os":{"loadavg":[3.90625,6.11376953125,8.89306640625],"uptime":892987},"trace":[{"column":11,"file":"/app/node_modules/mongodb-core/lib/topologies/server.js","function":null,"line":431,"method":null,"native":false},{"column":13,"file":"events.js","function":"Pool.emit","line":198,"method":"emit","native":false},{"column":14,"file":"/app/node_modules/mongodb-core/lib/connection/pool.js","function":"connect","line":557,"method":null,"native":false},{"column":5,"file":"/app/node_modules/mongodb-core/lib/connection/connect.js","function":"callback","line":109,"method":null,"native":false},{"column":7,"file":"/app/node_modules/mongodb-core/lib/connection/connect.js","function":"runCommand","line":129,"method":null,"native":false},{"column":5,"file":"/app/node_modules/mongodb-core/lib/connection/connect.js","function":"Connection.errorHandler","line":321,"method":"errorHandler","native":false},{"column":20,"file":"events.js","function":"Object.onceWrapper","line":286,"method":"onceWrapper","native":false},{"column":13,"file":"events.js","function":"Connection.emit","line":198,"method":"emit","native":false},{"column":12,"file":"/app/node_modules/mongodb-core/lib/connection/connection.js","function":null,"line":350,"method":null,"native":false},{"column":20,"file":"events.js","function":"Object.onceWrapper","line":286,"method":"onceWrapper","native":false},{"column":13,"file":"events.js","function":"TLSSocket.emit","line":198,"method":"emit","native":false},{"column":12,"file":"net.js","function":"_handle.close","line":606,"method":"close","native":false},{"column":7,"file":"_tls_wrap.js","function":"TCP.done","line":388,"method":"done","native":false}]}
2019-09-10T22:25:45.115380+00:00 heroku[web.1]: State changed from starting to crashed
2019-09-10T22:25:45.035380+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2019-09-10T22:25:45.035882+00:00 app[web.1]: npm ERR! errno 1
2019-09-10T22:25:45.037140+00:00 app[web.1]: npm ERR! Vidly_Node.js@1.0.0 start: `node index.js`
2019-09-10T22:25:45.037317+00:00 app[web.1]: npm ERR! Exit status 1
2019-09-10T22:25:45.039203+00:00 app[web.1]: npm ERR!
2019-09-10T22:25:45.039592+00:00 app[web.1]: npm ERR! Failed at the Vidly_Node.js@1.0.0 start script.
2019-09-10T22:25:45.039950+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2019-09-10T22:25:45.048694+00:00 app[web.1]:
2019-09-10T22:25:45.048842+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2019-09-10T22:25:45.048919+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2019-09-10T22_25_45_042Z-debug.log
2019-09-10T22:25:45.099192+00:00 heroku[web.1]: Process exited with status 1

**Comment by AgusDG** [comment]
Hey @MrPaz, Im facing the same problem than you:

"uncaughtException: failed to connect to server [vidly-shard-00-01-9gnfk.mongodb.net:27017] on first connect [MongoNetworkError: connection 5 to vidly-shard-00-01-9gnfk.mongodb.net:27017 closed]"

I can perfectly connect to my db on Compass, but Im getting the same error. Did you solve it?

**Comment by AgusDG** [comment]
Solved. When you receive an error like "MongoError: connection 4 to vidly-shard-00-01-dosly.mongodb.net:27017 closed" you have to whitelist all IP addresses in MongoDB security options.

**Step #2: In MongoDB Atlas, WHITELIST ALL IP ADDRESSES.**
As of May 2019, you can do this by going to Security (left panel) => Network Access => Actions (center-right) => EDIT => Whitelist Entry: => 0.0.0.0/0.

I followed the steps in this post in the forum.

[https://forum.codewithmosh.com/d/694-may-2019-summary-of-react-tutorial-vidly-node-deployment-fixes](https://forum.codewithmosh.com/d/694-may-2019-summary-of-react-tutorial-vidly-node-deployment-fixes)

**Comment by Adhikari1996** [comment]
Error connecting to mongoDB in heroku deploy.can anybody help me from it.mosh did depoly his db into mlab but cloud mongoDB is different ...when i used heroku config:set vidly_db='mongodb+srv://admin:<password>@cluster0.rqztp.mongodb.net/<dbname>?retryWrites=true&w=majority' ..i got some logs but i did cross check all cloud mongoDB cluster or path.still i got error...pls help me out...


here is my log--

2021-02-14T14:38:13.300433+00:00 app[web.1]: method: 'openUri',
2021-02-14T14:38:13.300456+00:00 app[web.1]: native: false
2021-02-14T14:38:13.300456+00:00 app[web.1]: },
2021-02-14T14:38:13.300456+00:00 app[web.1]: {
2021-02-14T14:38:13.300456+00:00 app[web.1]: column: 15,
2021-02-14T14:38:13.300457+00:00 app[web.1]: file: '/app/node_modules/mongoose/lib/index.js',
2021-02-14T14:38:13.300457+00:00 app[web.1]: function: 'Mongoose.connect',
2021-02-14T14:38:13.300457+00:00 app[web.1]: line: 206,
2021-02-14T14:38:13.300457+00:00 app[web.1]: method: 'connect',
2021-02-14T14:38:13.300457+00:00 app[web.1]: native: false
2021-02-14T14:38:13.300458+00:00 app[web.1]: },
2021-02-14T14:38:13.300458+00:00 app[web.1]: {
2021-02-14T14:38:13.300458+00:00 app[web.1]: column: 12,
2021-02-14T14:38:13.300458+00:00 app[web.1]: file: '/app/startup/db.js',
2021-02-14T14:38:13.300458+00:00 app[web.1]: function: 'module.exports',
2021-02-14T14:38:13.300459+00:00 app[web.1]: line: 7,
2021-02-14T14:38:13.300459+00:00 app[web.1]: method: 'exports',
2021-02-14T14:38:13.300459+00:00 app[web.1]: native: false
2021-02-14T14:38:13.300459+00:00 app[web.1]: },
2021-02-14T14:38:13.300459+00:00 app[web.1]: {
2021-02-14T14:38:13.300460+00:00 app[web.1]: column: 24,
2021-02-14T14:38:13.300460+00:00 app[web.1]: file: '/app/index.js',
2021-02-14T14:38:13.300460+00:00 app[web.1]: function: null,
2021-02-14T14:38:13.300460+00:00 app[web.1]: line: 9,
2021-02-14T14:38:13.300460+00:00 app[web.1]: method: null,
2021-02-14T14:38:13.300461+00:00 app[web.1]: native: false
2021-02-14T14:38:13.300461+00:00 app[web.1]: },
2021-02-14T14:38:13.300461+00:00 app[web.1]: {
2021-02-14T14:38:13.300461+00:00 app[web.1]: column: 30,
2021-02-14T14:38:13.300462+00:00 app[web.1]: file: 'internal/modules/cjs/loader.js',
2021-02-14T14:38:13.300462+00:00 app[web.1]: function: 'Module._compile',
2021-02-14T14:38:13.300462+00:00 app[web.1]: line: 1063,
2021-02-14T14:38:13.300462+00:00 app[web.1]: method: '_compile',
2021-02-14T14:38:13.300462+00:00 app[web.1]: native: false
2021-02-14T14:38:13.300463+00:00 app[web.1]: },
2021-02-14T14:38:13.300463+00:00 app[web.1]: {
2021-02-14T14:38:13.300463+00:00 app[web.1]: column: 10,
2021-02-14T14:38:13.300463+00:00 app[web.1]: file: 'internal/modules/cjs/loader.js',
2021-02-14T14:38:13.300463+00:00 app[web.1]: function: 'Module._extensions..js',
2021-02-14T14:38:13.300464+00:00 app[web.1]: line: 1092,
2021-02-14T14:38:13.300464+00:00 app[web.1]: method: '.js',
2021-02-14T14:38:13.300464+00:00 app[web.1]: native: false
2021-02-14T14:38:13.300464+00:00 app[web.1]: },
2021-02-14T14:38:13.300464+00:00 app[web.1]: {
2021-02-14T14:38:13.300465+00:00 app[web.1]: column: 32,
2021-02-14T14:38:13.300465+00:00 app[web.1]: file: 'internal/modules/cjs/loader.js',
2021-02-14T14:38:13.300465+00:00 app[web.1]: function: 'Module.load',
2021-02-14T14:38:13.300465+00:00 app[web.1]: line: 928,
2021-02-14T14:38:13.300465+00:00 app[web.1]: method: 'load',
2021-02-14T14:38:13.300472+00:00 app[web.1]: native: false
2021-02-14T14:38:13.300472+00:00 app[web.1]: },
2021-02-14T14:38:13.300473+00:00 app[web.1]: {
2021-02-14T14:38:13.300473+00:00 app[web.1]: column: 14,
2021-02-14T14:38:13.300473+00:00 app[web.1]: file: 'internal/modules/cjs/loader.js',
2021-02-14T14:38:13.300473+00:00 app[web.1]: function: 'Module._load',
2021-02-14T14:38:13.300473+00:00 app[web.1]: line: 769,
2021-02-14T14:38:13.300474+00:00 app[web.1]: method: '_load',
2021-02-14T14:38:13.300474+00:00 app[web.1]: native: false
2021-02-14T14:38:13.300474+00:00 app[web.1]: },
2021-02-14T14:38:13.300474+00:00 app[web.1]: {
2021-02-14T14:38:13.300475+00:00 app[web.1]: column: 12,
2021-02-14T14:38:13.300475+00:00 app[web.1]: file: 'internal/modules/run_main.js',
2021-02-14T14:38:13.300475+00:00 app[web.1]: function: 'Function.executeUserEntryPoint [as runMain]',
2021-02-14T14:38:13.300476+00:00 app[web.1]: line: 72,
2021-02-14T14:38:13.300476+00:00 app[web.1]: method: 'executeUserEntryPoint [as runMain]',
2021-02-14T14:38:13.300476+00:00 app[web.1]: native: false
2021-02-14T14:38:13.300476+00:00 app[web.1]: }
2021-02-14T14:38:13.300476+00:00 app[web.1]: ],
2021-02-14T14:38:13.300477+00:00 app[web.1]: stack: [
2021-02-14T14:38:13.300477+00:00 app[web.1]: 'Error: Username containing an unescaped at-sign',
2021-02-14T14:38:13.300477+00:00 app[web.1]: '    at parseConnectionString (/app/node_modules/mongodb/lib/url_parser.js:169:13)',
2021-02-14T14:38:13.300478+00:00 app[web.1]: '    at parseHandler (/app/node_modules/mongodb/lib/url_parser.js:112:14)',
2021-02-14T14:38:13.300478+00:00 app[web.1]: '    at module.exports (/app/node_modules/mongodb/lib/url_parser.js:19:12)',
2021-02-14T14:38:13.300478+00:00 app[web.1]: '    at /app/node_modules/mongoose/lib/connection.js:330:5',
2021-02-14T14:38:13.300479+00:00 app[web.1]: '    at Promise._execute (/app/node_modules/bluebird/js/release/debuggability.js:300:9)',
2021-02-14T14:38:13.300479+00:00 app[web.1]: '    at Promise._resolveFromExecutor (/app/node_modules/bluebird/js/release/promise.js:483:18)',
2021-02-14T14:38:13.300479+00:00 app[web.1]: '    at new Promise (/app/node_modules/bluebird/js/release/promise.js:79:10)',
2021-02-14T14:38:13.300479+00:00 app[web.1]: '    at NativeConnection.Connection.openUri (/app/node_modules/mongoose/lib/connection.js:329:17)',
2021-02-14T14:38:13.300480+00:00 app[web.1]: '    at Mongoose.connect (/app/node_modules/mongoose/lib/index.js:206:15)',
2021-02-14T14:38:13.300480+00:00 app[web.1]: '    at module.exports (/app/startup/db.js:7:12)',
2021-02-14T14:38:13.300480+00:00 app[web.1]: '    at Object.<anonymous> (/app/index.js:9:24)',
2021-02-14T14:38:13.300480+00:00 app[web.1]: '    at Module._compile (internal/modules/cjs/loader.js:1063:30)',
2021-02-14T14:38:13.300481+00:00 app[web.1]: '    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)',
2021-02-14T14:38:13.300481+00:00 app[web.1]: '    at Module.load (internal/modules/cjs/loader.js:928:32)',
2021-02-14T14:38:13.300481+00:00 app[web.1]: '    at Function.Module._load (internal/modules/cjs/loader.js:769:14)',
2021-02-14T14:38:13.300481+00:00 app[web.1]: '    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)'
2021-02-14T14:38:13.300486+00:00 app[web.1]: ]
2021-02-14T14:38:13.300486+00:00 app[web.1]: }
2021-02-14T14:38:13.322468+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2021-02-14T14:38:13.322854+00:00 app[web.1]: npm ERR! errno 1
2021-02-14T14:38:13.328032+00:00 app[web.1]: npm ERR! vidly@1.0.0 start: `node index.js`
2021-02-14T14:38:13.328136+00:00 app[web.1]: npm ERR! Exit status 1
2021-02-14T14:38:13.328252+00:00 app[web.1]: npm ERR!
2021-02-14T14:38:13.328351+00:00 app[web.1]: npm ERR! Failed at the vidly@1.0.0 start script.
2021-02-14T14:38:13.328436+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2021-02-14T14:38:13.337039+00:00 app[web.1]:
2021-02-14T14:38:13.337152+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2021-02-14T14:38:13.337218+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2021-02-14T14_38_13_329Z-debug.log
2021-02-14T14:38:13.401482+00:00 heroku[web.1]: Process exited with status 1
2021-02-14T14:38:13.476121+00:00 heroku[web.1]: State changed from starting to crashed




my connection string---

i did changed my password or db.
mongodb+srv://admin:<password>@cluster0.rqztp.mongodb.net/<dbname>?retryWrites=true&w=majority


everything is setup perfectly...but i don't know whats going here-

**Comment by udayaugustin** [comment]
Please check the connection string after whitelisting the API.

The connection string will look like below  for node 3.6 or later.
sample connection string :  `<vairablename>`=mongodb+srv://`<user>`:`<password>`@vidly.wrejo.mongodb.net/`<dbname>`?retryWrites=true&w=majority
sample environment variable : heroku config:set` <vairablename>`=mongodb+srv://`<user>`:`<password>`@vidly.wrejo.mongodb.net/`<dbname>`?retryWrites=true&w=majority

For an earlier version, you need to get the appropriate string from the MongoDB Atlas.
In dashboard Click  Connect-> Connect your application -> Choose the version. You can see the connection string specific to that version.

<img width="589" alt="Screenshot 2021-04-07 at 3 23 35 PM" src="https://user-images.githubusercontent.com/4465169/113847603-46585180-97b5-11eb-896b-367bcee47314.png">

**Comment by alisadeghi98** [comment]
any update ?
