### ISSUE TITLE
npm test fails with Error: Cannot find module 'walker'

### ISSUE THREAD

**Issue by ybakhshi** [mosh-hamedani/vidly-api-node#26]
> vidly@1.0.0 test C:\projects\vidly-api-node
> jest --watchAll --verbose --runInBand

Error: Cannot find module 'walker'
Require stack:
- C:\projects\vidly-api-node\node_modules\sane\src\common.js
- C:\projects\vidly-api-node\node_modules\sane\src\node_watcher.js
- C:\projects\vidly-api-node\node_modules\sane\index.js
- C:\projects\vidly-api-node\node_modules\jest\node_modules\jest-cli\node_modules\jest-haste-map\build\index.js
- C:\projects\vidly-api-node\node_modules\jest\node_modules\jest-cli\node_modules\jest-runtime\build\index.js
- C:\projects\vidly-api-node\node_modules\jest\node_modules\jest-cli\build\cli\index.js
- C:\projects\vidly-api-node\node_modules\jest\node_modules\jest-cli\bin\jest.js
- C:\projects\vidly-api-node\node_modules\jest\bin\jest.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\projects\vidly-api-node\node_modules\sane\src\common.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
npm ERR! Test failed.  See above for more details.

**Comment by sajib21** [comment]
@ybakhshi did you solve this issue?

**Comment by ybakhshi** [comment]
@sajib21 unfortunately, it was a long time back. i think  i didn't and left the course for another one on Udemy.

**Comment by benkham** [comment]
@sajib21 Issue was due to old Jest package. Uninstall and install jest to solve the issue.

Uninstall jest - npm uninstall jest
Install current version - npm install jest

**Comment by rajAmukhliS** [comment]
@benkham jazakALLAH buddy this really works 
thanks :)
