### ISSUE TITLE
Integration tests are failing randomly

### ISSUE THREAD

**Issue by jakimcho** [mosh-hamedani/vidly-api-node#6]
## Summary
Integration tests fail in a random manner. 

## Steps
1. Run `npm test`

## Result:
Some integration tests are failing with: 
```
...................

auth middleware
    ✕ should return 401 if no token is provided (342ms)
    ✕ should return 400 if token is invalid (132ms)
    ✓ should return 200 if token is valid (122ms)

  ● auth middleware › should return 401 if no token is provided

    listen EADDRINUSE :::3900

      12 | 
      13 | const port = process.env.PORT || config.get("port");
    > 14 | const server = app.listen(port, () =>
      15 |   winston.info(`Listening on port ${port}...`)
      16 | );

...............
```
## Expected Result
All tests (unit and integration) should pass

## Probable reason 
Race condition. The server has not been stopped on time when the next test cases initiates.

**Comment by yardenshoham** [comment]
I have the same issue. I believe more people are having this problem at #12.

Edit: It seems a solution was provided in #1. [Here's the comment with the solution.](https://github.com/mosh-hamedani/vidly-api-node/issues/1#issuecomment-419666200)

**Comment by ybakhshi** [comment]
> vidly@1.0.0 test C:\projects\vidly-api-node
> jest --watchAll --verbose --runInBand

Error: Cannot find module 'walker'
Require stack:
- C:\projects\vidly-api-node\node_modules\sane\src\common.js
- C:\projects\vidly-api-node\node_modules\sane\src\node_watcher.js
- C:\projects\vidly-api-node\node_modules\sane\index.js
- C:\projects\vidly-api-node\node_modules\jest\node_modules\jest-cli\node_modules\jest-haste-map\build\index.js
- C:\projects\vidly-api-node\node_modules\jest\node_modules\jest-cli\node_modules\jest-runtime\build\index.js
- C:\projects\vidly-api-node\node_modules\jest\node_modules\jest-cli\build\cli\index.js
- C:\projects\vidly-api-node\node_modules\jest\node_modules\jest-cli\bin\jest.js
- C:\projects\vidly-api-node\node_modules\jest\bin\jest.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\projects\vidly-api-node\node_modules\sane\src\common.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
npm ERR! Test failed.  See above for more details.
